window.onload = function() {
    console. log("saludos, Hola Juan MP");
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");hola
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    console. log("saludos, Hola Juan MP");abajo
    
}
